services:
  db:
    image: postgres:16-alpine
    container_name: flowershop-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Обязательно подпапка /data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./FlowerShopBackend
      dockerfile: Dockerfile
    container_name: flowershop_backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Динамическая сборка без открытых паролей:
      - ConnectionStrings__DbConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=FlowerShopAPI
      - JwtSettings__Audience=FlowerShopClient
      - JwtSettings__ExpiryHours=12
    volumes:
      - uploads_data:/app/wwwroot/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M